### PR TITLE
AERecorder: expose recording BOOL property. Stop recording at error.

### PR DESCRIPTION
**Pull request by lijon**

### CODE REVIEW

**Comment by edsharp** [comment]
Hey guys, my project is ARC-enabled and so Xcode doesn't like the [super dealloc] call in AERecorder.m.

Also, it's unhappy with the pointer casting and would prefer a __bridge on the finishRecording call in reportError:

[((__bridge AERecorder*)arg->THIS) finishRecording];

**Comment by lijon** [comment]
How is the rest of AERecorder.m written? If it's non-ARC, then you could
just disable ARC for this file.

On Sat, May 30, 2015 at 5:18 PM, edsharp <notifications@github.com> wrote:

> Hey guys, my project is ARC-enabled and so Xcode doesn't like the [super
> dealloc] call in AERecorder.m.
>
> Also, it's unhappy with the pointer casting and would prefer a __bridge on
> the finishRecording call in reportError:
>
> [((__bridge AERecorder*)arg->THIS) finishRecording];
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/pull/147#issuecomment-107052441>
> .
>



-- 
/Jonatan
http://kymatica.com

**Comment by edsharp** [comment]
I'm guessing all the TAAE code should be written for ARC given that http://theamazingaudioengine.com/doc/_getting-_started.html states:

Note that TAAE now uses ARC, so if you're including source files directly within your non-ARC project, you'll need to add the -fobjc-arc flag to the build parameters for each source file, which you can do by opening the "Build Phases" tab of your app target, opening the "Compile Sources" section, and double-clicking in the "Compiler Flags" column of the relevant source files.

I have installed it using CocoaPods, but referencing the current master rather than a tag.

I'm curious as to how you were able to compile this without errors. My temporary fixes have been to remove the super dealloc call and add the bridging cast.

**Comment by lijon** [comment]
AERecorder isn't compiled within TAAE, but has to be copied into your own
project. And my own project is non-ARC (haven't converted it to ARC yet),
so that's why it compiles fine.

On Tue, Jun 2, 2015 at 4:10 PM, edsharp <notifications@github.com> wrote:

> I'm guessing all the TAAE code should be written for ARC given that
> http://theamazingaudioengine.com/doc/_getting-_started.html states:
>
> Note that TAAE now uses ARC, so if you're including source files directly
> within your non-ARC project, you'll need to add the -fobjc-arc flag to the
> build parameters for each source file, which you can do by opening the
> "Build Phases" tab of your app target, opening the "Compile Sources"
> section, and double-clicking in the "Compiler Flags" column of the relevant
> source files.
>
> I have installed it using CocoaPods, but referencing the current master
> rather than a tag.
>
> I'm curious as to how you were able to compile this without errors. My
> temporary fixes have been to remove the super dealloc call and add the
> bridging cast.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine/pull/147#issuecomment-107968510>
> .
>



-- 
/Jonatan
http://kymatica.com

**Comment by edsharp** [comment]
Oh ok. I have to say, having never made a pod, I'm not sure how the compilation is working. I've just used it blindly and it's all worked in the past. 

I'm pretty sure I'm in a minority of people using TAAE master as a pod. I have the following in my Podfile:

pod 'TheAmazingAudioEngine', :git => 'https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine.git'

But once Michael makes a new tag of TAAE and the majority of people start using this, I'm pretty sure others will find this error, too, with their setups.

The ARC restrictions error shows up under the Pods-TheAmazingAudioEngine target if I try to run my project. 

It's really easy to re-create - just make a new 1-page app project. pod init it and add the pod line I have from above. pod install and then open the workspace and build your project. That's it. Pods-TheAmazingAudioEngine will raise the errors.

**Comment by michaeltyson** [comment]
Bugger, yeah, this is definitely a problem - I've been on holiday, so I just merged this on faith, but you're right; it breaks. Can you fix that @lijon?

**Comment by lijon** [comment]
Ok, will try to have a look at that soon!

/Jonatan

**Comment by cjhanson** [comment]
I made the change in my fork and submitted a pull request.

**Comment by michaeltyson** [comment]
Perfect! Cheers =)

**Pull request merged**
