### PR TITLE
Enable audio input for OSX

### PR DESCRIPTION
**Pull request by srubin**
Added additional audio unit to handle input because no audio unit can
handle IO on OSX like remoteIO can on iOS.

Updated the OSX sample app with input and recording capabilities.

### CODE REVIEW

**Comment by michaeltyson** [comment]
*applause*

**Comment by michaeltyson** [comment]
There seems to be some weird stuff going on with the input rate, maybe - hitting record and saying stuff results in chipmunk mode =) http://cl.ly/1N1A3h200y0j

**Comment by srubin** [comment]
I'm guessing your input mic was set to record at 16 KHz (your recording sounds reasonable when played with that sample rate). I'll add support for sample rate conversion.

**Comment by michaeltyson** [comment]
Ah, right! Cool =) Great work!

**Pull request merged**
