### PR TITLE
Change sample rate of OSX hardware input to match desired output

### PR DESCRIPTION
**Pull request by srubin**

### CODE REVIEW

**Comment by michaeltyson** [comment]
No joy, I'm afraid - it's still behaving very strangely on my system. It works with my Komplete Audio 6 interface and the built-in mic, but the external USB camera I'm using isn't providing any input and I'm seeing a lot of "AEAudioController.m:686: AudioUnitRender result -10863 "

**Comment by michaeltyson** [comment]
Oh, this is the interesting error, not the other one:

2015-08-17 14:02:35.893 TheEngineSampleOSX[12588:1765847] TAAE: AEAudioController.m:2867: AudioObjectSetPropertyData(kAudioDevicePropertyNominalSampleRate) result 560226676 21646174 !dat

**Comment by srubin** [comment]
Okay. I assume you're getting `TAAE: Warning: could not set hardware input to same sample rate as output` right before that line as well?

This means your webcam is unable to record at your target output samplerate. It doesn't make a lot of sense to have a microphone providing input at the wrong samplerate in an audio application. We could try to change the output samplerate to match the input samplerate if we can't do the opposite.

How do you think TAAE should behave when the input device can't match the output device's samplerate?

Also---just curious---what samplerates does your USB camera support (e.g., in Audio Midi Setup).

**Comment by michaeltyson** [comment]
Whoops, my bad, yes, it is indeed. 

I think the best approach would be to try to set the input rate, but if it fails, to introduce an audio converter on the input, the same way that AEAudioUnitChannel/Filter works. AEAudioController already adds an audio converter to the input if it's required (see AEAudioController.m:3155 and surroundings), so it should be pretty straightforward to use that.

**Comment by srubin** [comment]
Ok. That sounds similar to my previous approach, so it should be a quick
change. Will do.

**Pull request merged**
