### PR TITLE
RMS levels

### PR DESCRIPTION
**Pull request by 32Beat**
PLEASE NOTE: further cleanup recommended, would be nice to have a "develop" branch

I added some files for a different take on RMS level metering, the files should however be placed in a common folder/group. Further cleanup of the current viewcontrollers is recommended, but I would like to submit this before continuing in order to have discussion/suggestions on how to proceed.  

Added: 
- RMSLevels folder including an engine and views
- rewrite of viewcontroller, specifically the Mac version to fetch view from nib

the latter part needs further implementation/cleanup so it either consistently uses nib, or not at all.

### CODE REVIEW

**Comment by michaeltyson** [comment]
I'd suggest this might be best implemented like the oscilloscope view: one class that also acts as a receiver. Also, I think it's best to use vector math using Accelerate, rather than sample-by-sample; it'll be much more efficient.

**Comment by 32Beat** [comment]
Okay, I'll work on that. 

Is it safe to assume that output receivers should not modify the samples? Perhaps it might be possible to call outputreceivers on separate threads? e.g.:

1. copy output buffers
2. let the HAL consume and reuse original output buffers
3. supply the copy of buffers to outputreceivers on separate threads.

**Comment by michaeltyson** [comment]
I don't think I understand your question, I'm afraid

**Comment by 32Beat** [comment]
The Oscilloscope layer for example seems to copy the incoming samples to its own buffer, which means it could subsequently do processing in a separate thread, instead of in the audio thread. 

Similarly, all output receivers could be on separate threads as long as the integrity of the sample buffers is guaranteed. The original AudioBufferList is likely rotated by the output audio queue, but a copy can be managed by the AEAudioController.

**Comment by michaeltyson** [comment]
I don't think that's a good idea. If an output receiver needs to move the data to a separate thread, or edit the data, it should create a copy.

**Pull request closed without merging**
